var myString;
var myNum;
var myBool;
var myVar;
var strArr;
var numArr;
var boolArr;
var strArr2;
var numArr2;
var boolArr2;
var strNumTuple;
var myVoid = null;
var myNull = null = null;
var myUndefined = null;
myString = 'Hello World!';
myNum = 24;
myBool = true;
myVar = 5;
strArr = ['Hello', 'World'];
numArr = [1, 2, 3];
boolArr = [true, true, false];
strArr2 = ['Hello', 'World'];
numArr2 = [1, 2, 3];
boolArr2 = [true, true, false];
strNumTuple = ['Victor', 24];
console.log(myString);
console.log(myNum);
console.log(myBool);
console.log(myVar);
console.log(strArr);
console.log(numArr);
console.log(boolArr);
console.log(strArr2);
console.log(numArr2);
console.log(boolArr2);
console.log(strNumTuple);
console.log(myVoid);
